# Generated by Django 4.0.5 on 2022-06-22 20:29

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('status', models.TextField(choices=[('new', 'Новый сотрудник'), ('replace', 'Замена')], default='new')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('location', models.TextField(default='Кировская область, г. Киров')),
                ('project', models.TextField()),
                ('salary', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.department')),
            ],
        ),
    ]
