# Generated by Django 4.0.5 on 2022-06-26 20:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('age', models.PositiveSmallIntegerField()),
                ('position', models.TextField()),
                ('salary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('update_date', models.DateTimeField()),
                ('position', models.TextField()),
                ('experience', models.PositiveSmallIntegerField()),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('salary', models.PositiveIntegerField()),
                ('detailed_experience', models.TextField()),
                ('about', models.TextField()),
                ('phase', models.TextField(choices=[('added', 'Новый сотрудник'), ('phone_interview', 'Телефонное интервью'), ('hr_interview_scheduled', 'Назначено интервью с рекрутом'), ('hr_interview_primary', 'Первичное интервью с рекрутом'), ('resume_at_customer', 'Резюме у заказчика'), ('test_task', 'Тестовое задание'), ('customer_interview_scheduled', 'Назначено интервью с заказчиком')], default='added')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.candidate')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.resumesource')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.candidate')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.contacttype')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.citizenship'),
        ),
    ]
