# Generated by Django 4.0.5 on 2022-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_candidate_citizenship_contacttype_resumesource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='resume',
            field=models.ManyToManyField(to='backend.resume'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новый сотрудник'), (1, 'Телефонное интервью'), (2, 'Назначено интервью с рекрутом'), (3, 'Первичное интервью с рекрутом'), (4, 'Резюме у заказчика'), (5, 'Тестовое задание'), (6, 'Назначено интервью с заказчиком')], default=0),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новый сотрудник'), (1, 'Замена')], default=0),
        ),
    ]
