# Generated by Django 4.0.5 on 2022-06-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_vacancy_resume_alter_resume_phase_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
