# Generated by Django 4.0.5 on 2022-06-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='contacts',
            field=models.ManyToManyField(through='backend.Contact', to='backend.contacttype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.candidate'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='backend.contacttype'),
        ),
    ]
