# Generated by Django 4.0.5 on 2022-06-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_resume_vacancy_resumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='salary',
            field=models.TextField(),
        ),
    ]
