# Generated by Django 4.0.5 on 2022-06-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_resume_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
