# Generated by Django 4.0.6 on 2022-07-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='phase',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новый сотрудник'), (1, 'Телефонное интервью'), (2, 'Назначено интервью с рекрутом'), (3, 'Первичное интервью с рекрутом'), (4, 'Резюме у заказчика'), (5, 'Тестовое задание'), (6, 'Назначено интервью с заказчиком'), (1000, 'ТЕСТ')], default=0),
        ),
    ]
